apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-rc
spec:
  tasks:
    - name: hello
      taskSpec:
        steps:
          - name: echo
            image: public.ecr.aws/docker/library/alpine:latest
            script: |
              #!/bin/sh
              echo "Hello from an embedded task inside a Pipeline!"

